leapt_froala_editor:
    language: en
    profiles:
        basic:
            language: fr
            toolbarButtons:
                - ['bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript']
                - ['fontFamily', 'fontSize', 'textColor', 'backgroundColor']
