version: '3'

tasks:
    fixtures:
        desc: Generate fixtures
        cmds:
            - rm -f var/data.db
            - symfony console d:s:c --quiet
            - symfony console d:s:u --force --quiet
            - symfony console a:f:l

    composer:
        desc: Install PHP vendors
        cmds:
            - symfony composer install
        sources:
            - composer.lock
        generates:
            - vendor/**/*

    start:
        desc: Start Symfony server
        cmds:
            - symfony serve -d

    stop:
        desc: Stop Symfony server
        cmds:
            - symfony server:stop

    lint:
        desc: Check code style, static analysis...
        cmds:
            - symfony console doctrine:schema:validate
            - symfony php vendor/bin/ecs
            - symfony php vendor/bin/twig-cs-fixer lint
            - symfony console biomejs:download --quiet
            - bin/biome check
            - task: phpstan
            - symfony console lint:twig templates
            - symfony console lint:yaml config translations
            - symfony composer audit

    cs-fix:
        desc: Fix code style
        cmds:
            - symfony php vendor/bin/ecs --fix
            - symfony php vendor/bin/twig-cs-fixer lint --fix
            - bin/biome check --write --unsafe

    phpstan:
        desc: Run PHPStan analysis
        cmds:
            - symfony php vendor/bin/phpstan analyse

    phpstan-baseline:
        desc: Generate PHPStan baseline
        cmds:
            - symfony php vendor/bin/phpstan analyse --generate-baseline

    test:
        desc: Run tests
        env:
            APP_ENV: test
        cmds:
            - symfony php vendor/bin/phpunit

    ci:
        desc: Run lint & tests
        cmds:
            - task: lint
            - task: test
