name: PHPUnit

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

env:
  APP_ENV: test

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php-version:
          - '8.4'

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPUnit
        run: vendor/bin/phpunit
